githubConfigUrl: "https://github.com/dvystrcil/open-terminal-docker" 
# controllerServiceAccount:
#   namespace: arc-systems
#   name: arc-systems-gha-rs-controller 
# githubConfigSecret: arc-secret
runnerScaleSetName: "open-terminal-docker-runner"
minRunners: 0
maxRunners: 3
